[book]
authors = ["Antoine de Saint-Exupéry","Thomas Schmidt"]
language = "ie"
multilingual = false
src = "src"
title = "Li Litt Prince"

[output.html]
theme = "src/theme"
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/occidental-lang/LiLittPrince"
site-url = "/LiLittPrince/"

[output.html.fold]
enable = false

[build]
build-dir = "docs"
